name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r chatbot/requirements.txt
        pip install -r app/requirements.txt

    - name: Run tests
      run: |
        # Example of running tests, you can adjust based on your testing framework
        pytest

    - name: Build Docker image
      run: |
        docker build -t my-app .

    - name: Deploy to Cloud
      run: |
        # Replace this with actual deployment commands, e.g., Heroku, AWS, etc.
        bash deploy/deploy.sh
        
    - name: Notify on Slack via Bot
      env:
        SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data "{\"channel\":\"$SLACK_CHANNEL_ID\",\"text\":\"Deployment Successful!\"}" \
        "https://slack.com/api/chat.postMessage?token=$SLACK_API_TOKEN"
